global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using BepInEx;
global using BepInEx.Configuration;
global using BepInEx.Logging;
global using Comfort.Common;
global using EFT;
global using EFT.Animations;
global using EFT.Communications;
global using EFT.HandBook;
global using EFT.HealthSystem;
global using EFT.InputSystem;
global using EFT.Interactive;
global using EFT.InventoryLogic;
global using EFT.UI;
global using GPUInstancer;
global using HarmonyLib;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using SPT.Common.Http;
global using Systems.Effects;
global using UnityEngine;
global using UnityEngine.Rendering;
global using UnityEngine.UI;
global using Object = UnityEngine.Object;

global using PoolManagerClass = EFT.ObjectsFactory;
global using BotCreationDataClass = BotCreationData;
global using HandbookClass = EFT.HandBook.Handbook;
global using ItemFactoryClass = EFT.ItemFactory;
global using IKillableLootItem = IKillable;
global using CameraClass = EFT.CameraControl.CameraManager;
global using EftBulletClass = EFT.Ballistics.Shot;
global using DamageInfoStruct = EFT.Ballistics.DamageInfo;
global using RagFairClass = EFT.UI.Ragfair.RagFair;
global using TraderControllerClass = EFT.InventoryLogic.ItemController;
global using MagazineItemClass = EFT.InventoryLogic.Magazine;
global using AmmoItemClass = EFT.InventoryLogic.Ammo;
global using AddItemEventArgs = EFT.InventoryLogic.AddItemEventArgs;
global using RemoveItemEventArgs = EFT.InventoryLogic.RemoveItemEventArgs;
global using RefreshItemEventArgs = EFT.InventoryLogic.RefreshItemEventArgs;
