//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Hysocs")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("In-raid administration and testing utilities for SPT users and mod developers.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.2.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.2.0+7f4cda4445e1adb60df40a8bd55b050de10bcc1c")]
[assembly: System.Reflection.AssemblyProductAttribute("FieldKit — Developer Tools for SPT")]
[assembly: System.Reflection.AssemblyTitleAttribute("FieldKit")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.2.0")]

// Generated by the MSBuild WriteCodeFragment class.

